import "./globals.css";

import Modal from "@/shared/ui/Modal";

export const metadata = {
  title: "ToDo App",
  description: "Generated by pdvkchtt",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
